Crash bug when processing SSO return under Xcode 9.3 (#233)
* Fixed an issue that appears when compiled with Xcode 9.3, where the various "annotation" parameters are declared as "Any", which means that they cannot be nil.  With the new version of the compiler, a nil value causes a runtime crash, and the source of this parameter, the application's incoming value for options[UIApplicationOpenURLOptionsAnnotationKey] is typically nil. Passing a nil value as annotation directly actually results in the following compilation error: "Null passed to a callee that requires a non-null argument", as further evidence of the issue.  The fix is to make annotation an optional parameter ("Any?" instead of "Any") in the various places it is used.

* Fixed a few more places where "annotation" was declared as "Any", instead of "Any?" (i.e. optional, since it can be nil).